abstract: WSDL/WADL-like interface make for WebService::Simple.
author: Kazuhiro Osawa <ko@yappo.ne.jp>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: WebService-Simple-Cabinet
no_index: 
  directory: 
    - inc
    - t
requires: 
  UNIVERSAL::require: 0
  WebService::Simple: 0
version: 0.01
